export const navigation = [
  { href: "/search?mode=stay", label: "Stays" },
  { href: "/search?mode=rent", label: "Rent" },
  { href: "/search?mode=buy", label: "Buy" },
  { href: "/search?mode=new", label: "New homes" },
  { href: "/social", label: "Community" },
];

export const areas = [
  { name: "Maitama", count: 48, note: "Diplomatic calm, destination dining", image: "/images/nestora/maitama-villa.webp" },
  { name: "Jabi", count: 72, note: "Lake life, cafés, easy connections", image: "/images/nestora/jabi-community.webp" },
  { name: "Guzape", count: 55, note: "Hillside homes and new estates", image: "/images/nestora/guzape-duplex.webp" },
  { name: "Katampe", count: 36, note: "Elevated views, considered design", image: "/images/nestora/katampe-residences.webp" },
];

const catalogueProperties = [
  {
    id: "wuye-courtyard-residence",
    mode: "rent",
    title: "The Courtyard Residence",
    area: "Wuye",
    location: "Wuye, Abuja",
    address: "Quiet residential close, Wuye District",
    price: 8500000,
    cadence: "year",
    beds: 3,
    baths: 3.5,
    guests: 6,
    sqm: 218,
    rating: 4.92,
    reviews: 38,
    image: "/images/nestora/wuye-apartment.webp",
    gallery: [
      "/images/nestora/wuye-apartment.webp",
      "/images/nestora/jabi-serviced-suite.webp",
      "/images/nestora/guzape-duplex.webp",
      "/images/nestora/katampe-residences.webp",
    ],
    verified: true,
    fresh: "Updated today",
    tag: "Virtual tour",
    host: "Amina Bello",
    hostId: "amina-bello",
    description: "A quiet, design-led apartment with generous rooms, dependable power and a planted private courtyard. Finished in walnut, local stone and hand-selected Nigerian art.",
    highlights: ["Dedicated inverter and generator", "24-hour estate security", "Two covered parking bays", "Professionally managed"],
    amenities: ["Fibre internet", "Air conditioning", "Fitted kitchen", "Laundry room", "Smart access", "Water treatment"],
    fees: { rent: 8500000, agency: 850000, legal: 425000, service: 620000 },
    lat: 9.055,
    lng: 7.436,
  },
  {
    id: "maitama-ridge-villa",
    mode: "buy",
    title: "Maitama Ridge Villa",
    area: "Maitama",
    location: "Maitama, Abuja",
    address: "Near Ministers' Hill, Maitama",
    price: 685000000,
    cadence: "total",
    beds: 5,
    baths: 6,
    guests: 10,
    sqm: 740,
    rating: 4.98,
    reviews: 19,
    image: "/images/nestora/maitama-villa.webp",
    gallery: [
      "/images/nestora/maitama-villa.webp",
      "/images/nestora/wuye-apartment.webp",
      "/images/nestora/asokoro-rooftop.webp",
      "/images/nestora/katampe-residences.webp",
    ],
    verified: true,
    fresh: "Verified 2 days ago",
    tag: "Exclusive",
    host: "Amina Bello",
    hostId: "amina-bello",
    description: "A restrained contemporary villa framed by mature gardens and Abuja's hills. Double-height living spaces, a private cinema, pool pavilion and calm material palette make this a rare family home.",
    highlights: ["Registered title documents", "Private pool and garden", "Solar-backed power system", "Staff quarters for four"],
    amenities: ["Cinema", "Pool", "Lift", "Wine room", "Gym", "CCTV", "Solar power", "Borehole"],
    fees: { purchase: 685000000, agency: 34250000, legal: 6850000 },
    lat: 9.095,
    lng: 7.493,
  },
  {
    id: "jabi-lake-serviced-suite",
    mode: "stay",
    title: "Jabi Lake Serviced Suite",
    area: "Jabi",
    location: "Jabi, Abuja",
    address: "Lakeview quarter, Jabi",
    price: 185000,
    cadence: "night",
    beds: 1,
    baths: 1,
    guests: 2,
    sqm: 62,
    rating: 4.89,
    reviews: 126,
    image: "/images/nestora/jabi-serviced-suite.webp",
    gallery: [
      "/images/nestora/jabi-serviced-suite.webp",
      "/images/nestora/jabi-community.webp",
      "/images/nestora/asokoro-rooftop.webp",
      "/images/nestora/wuye-apartment.webp",
    ],
    verified: true,
    fresh: "Available this weekend",
    tag: "Guest favourite",
    host: "The Nook Jabi",
    hostId: "the-nook-jabi",
    description: "A serene lake-facing suite with hotel-level service and the warmth of a private apartment. Walk to Jabi's best cafés, then return to sunset views and a deeply comfortable bed.",
    highlights: ["Daily housekeeping", "Breakfast included", "Airport transfer available", "Flexible self check-in"],
    amenities: ["Lake view", "Fast Wi-Fi", "Breakfast", "Pool", "Gym", "Kitchenette"],
    fees: { nightly: 185000, cleaning: 28000, service: 18500, taxes: 13875 },
    lat: 9.066,
    lng: 7.424,
  },
  {
    id: "guzape-garden-duplex",
    mode: "rent",
    title: "Guzape Garden Duplex",
    area: "Guzape",
    location: "Guzape, Abuja",
    address: "Upper Guzape, Abuja",
    price: 15000000,
    cadence: "year",
    beds: 4,
    baths: 5,
    guests: 8,
    sqm: 380,
    rating: 4.85,
    reviews: 24,
    image: "/images/nestora/guzape-duplex.webp",
    gallery: [
      "/images/nestora/guzape-duplex.webp",
      "/images/nestora/katampe-residences.webp",
      "/images/nestora/wuye-apartment.webp",
      "/images/nestora/maitama-villa.webp",
    ],
    verified: true,
    fresh: "Updated yesterday",
    tag: "Family ready",
    host: "Amina Bello",
    hostId: "amina-bello",
    description: "A bright end-terrace duplex with a private lawn, family lounge and thoughtful storage throughout. The secure estate sits above the city with quick links to Asokoro and Garki.",
    highlights: ["Private garden", "Fully fitted kitchen", "Quiet gated estate", "Two-room staff quarters"],
    amenities: ["Garden", "Study", "Family lounge", "Generator", "Borehole", "CCTV"],
    fees: { rent: 15000000, agency: 1500000, legal: 750000, service: 850000 },
    lat: 9.021,
    lng: 7.501,
  },
  {
    id: "asokoro-skyhouse",
    mode: "stay",
    title: "Asokoro Skyhouse",
    area: "Asokoro",
    location: "Asokoro, Abuja",
    address: "Diplomatic Drive, Asokoro",
    price: 320000,
    cadence: "night",
    beds: 2,
    baths: 2,
    guests: 4,
    sqm: 118,
    rating: 4.96,
    reviews: 83,
    image: "/images/nestora/asokoro-rooftop.webp",
    gallery: [
      "/images/nestora/asokoro-rooftop.webp",
      "/images/nestora/jabi-serviced-suite.webp",
      "/images/nestora/maitama-villa.webp",
      "/images/nestora/wuye-apartment.webp",
    ],
    verified: true,
    fresh: "Instant confirmation",
    tag: "Rooftop pool",
    host: "Skyhouse Hospitality",
    hostId: "skyhouse",
    description: "A polished city stay with an exceptional rooftop pool, evening lounge and wide views toward Aso Rock. Every detail is tuned for effortless work trips and unhurried weekends.",
    highlights: ["Rooftop infinity pool", "On-site concierge", "Secure diplomatic district", "Late checkout on request"],
    amenities: ["Pool", "Rooftop bar", "Concierge", "Fast Wi-Fi", "Gym", "Breakfast"],
    fees: { nightly: 320000, cleaning: 35000, service: 32000, taxes: 24000 },
    lat: 9.04,
    lng: 7.522,
  },
  {
    id: "katampe-court-residences",
    mode: "new",
    title: "Katampe Court Residences",
    area: "Katampe",
    location: "Katampe Extension, Abuja",
    address: "Katampe Extension",
    price: 245000000,
    cadence: "from",
    beds: 3,
    baths: 4,
    guests: 6,
    sqm: 242,
    rating: 4.91,
    reviews: 11,
    image: "/images/nestora/katampe-residences.webp",
    gallery: [
      "/images/nestora/katampe-residences.webp",
      "/images/nestora/wuye-apartment.webp",
      "/images/nestora/guzape-duplex.webp",
      "/images/nestora/maitama-villa.webp",
    ],
    verified: true,
    fresh: "Phase 1 · 78% complete",
    tag: "New development",
    host: "Northline Developments",
    hostId: "northline",
    description: "Thirty-six considered homes around landscaped courts, a residents' pool and quiet social spaces. Construction updates, title documents and payment milestones are available in one verified project room.",
    highlights: ["Delivery Q2 2027", "Flexible payment milestones", "Independent progress reports", "FCDA-approved plans"],
    amenities: ["Residents' pool", "Co-working lounge", "Play garden", "Solar backup", "Lift", "Visitor parking"],
    fees: { purchase: 245000000, documentation: 2450000, infrastructure: 3800000 },
    lat: 9.112,
    lng: 7.481,
  },
  {
    id: "zuma-rock-retreat",
    mode: "stay",
    title: "Zuma Rock Retreat",
    area: "Madalla",
    location: "Abuja outskirts",
    address: "Near Zuma Rock, Niger State",
    price: 240000,
    cadence: "night",
    beds: 2,
    baths: 2,
    guests: 4,
    sqm: 96,
    rating: 4.94,
    reviews: 61,
    image: "/images/nestora/abuja-weekend-retreat.webp",
    gallery: [
      "/images/nestora/abuja-weekend-retreat.webp",
      "/images/nestora/asokoro-rooftop.webp",
      "/images/nestora/jabi-serviced-suite.webp",
      "/images/nestora/katampe-residences.webp",
    ],
    verified: true,
    fresh: "2 nights available",
    tag: "Weekend escape",
    host: "Afi Mountain Stays",
    hostId: "afi-stays",
    description: "A slow-living retreat woven between granite boulders, natural pools and green hills. Private villas pair quiet architecture with generous local hospitality, less than an hour from central Abuja.",
    highlights: ["Private plunge pool", "All meals available", "Guided landscape walks", "Complimentary city transfer"],
    amenities: ["Natural pool", "Full board", "Outdoor shower", "Fire pit", "Spa treatments", "Transfer"],
    fees: { nightly: 240000, cleaning: 25000, service: 24000, taxes: 18000 },
    lat: 9.142,
    lng: 7.219,
  },
];

export const properties = catalogueProperties.map((property) => ({ ...property, illustrative: true }));

const catalogueProfiles = [
  {
    id: "amina-bello",
    name: "Amina Bello",
    role: "Verified Property Advisor",
    company: "Bello & Co. Living",
    location: "Abuja, Nigeria",
    avatar: "/images/nestora/amina-bello-agent.webp",
    bio: "Helping families and professionals move through Abuja with clear information, careful viewings and no pressure.",
    followers: 4820,
    listings: 26,
    response: "Usually replies within 18 minutes",
    verified: true,
  },
  {
    id: "the-nook-jabi",
    name: "The Nook Jabi",
    role: "Hospitality Host",
    company: "The Nook Collection",
    location: "Jabi, Abuja",
    avatar: "/images/nestora/jabi-serviced-suite.webp",
    bio: "Calm, considered serviced stays by the lake.",
    followers: 2180,
    listings: 8,
    response: "Usually replies within 10 minutes",
    verified: true,
  },
];

export const profiles = catalogueProfiles.map((profile) => ({ ...profile, illustrative: true }));

export const communities = [
  { id: "living-in-abuja", name: "Living in Abuja", members: 18400, description: "Neighbourhood notes, move-in advice and the places worth knowing.", image: "/images/nestora/jabi-community.webp", privacy: "Public" },
  { id: "first-home-circle", name: "First Home Circle", members: 6200, description: "Practical support for buying well, from title checks to closing day.", image: "/images/nestora/katampe-residences.webp", privacy: "Public" },
  { id: "hosts-of-abuja", name: "Hosts of Abuja", members: 890, description: "A peer space for thoughtful hospitality operators.", image: "/images/nestora/asokoro-rooftop.webp", privacy: "Private" },
];

export const posts = [
  {
    id: "post-1",
    author: "Amina Bello",
    authorId: "amina-bello",
    avatar: "/images/nestora/amina-bello-agent.webp",
    verified: true,
    time: "38 min",
    text: "A useful viewing detail: visit this Wuye home between 4 and 5 pm. You will hear the estate at its busiest and see exactly how the courtyard catches the softer light.",
    image: "/images/nestora/wuye-apartment.webp",
    propertyId: "wuye-courtyard-residence",
    reactions: 148,
    comments: 21,
  },
  {
    id: "post-2",
    author: "Living in Abuja",
    authorId: "living-in-abuja",
    avatar: "/images/nestora/jabi-community.webp",
    verified: true,
    time: "2 hr",
    text: "Jabi on a Saturday: lake walk first, coffee after. We have updated the community guide with six quiet work-friendly spots and current parking notes.",
    image: "/images/nestora/jabi-community.webp",
    communityId: "living-in-abuja",
    reactions: 392,
    comments: 47,
  },
  {
    id: "post-3",
    author: "Northline Developments",
    authorId: "northline",
    avatar: "/images/nestora/katampe-residences.webp",
    verified: true,
    time: "Yesterday",
    text: "Katampe Court has reached roof level across all Phase 1 blocks. The independent engineer's June progress note is now available in the project room.",
    image: "/images/nestora/katampe-residences.webp",
    propertyId: "katampe-court-residences",
    reactions: 226,
    comments: 32,
  },
];

export const conversations = [
  { id: "conv-amina", name: "Amina Bello", avatar: "/images/nestora/amina-bello-agent.webp", preview: "I have held the 4:30 pm viewing for you.", time: "11:42", unread: 2, propertyId: "wuye-courtyard-residence" },
  { id: "conv-nook", name: "The Nook Jabi", avatar: "/images/nestora/jabi-serviced-suite.webp", preview: "Airport pickup can be added until 6 pm.", time: "Yesterday", unread: 0, propertyId: "jabi-lake-serviced-suite" },
  { id: "conv-northline", name: "Northline Developments", avatar: "/images/nestora/katampe-residences.webp", preview: "The title pack is ready in your documents.", time: "Mon", unread: 0, propertyId: "katampe-court-residences" },
];

export function getProperty(id) {
  return properties.find((property) => property.id === id);
}

export function getProfile(id) {
  return profiles.find((profile) => profile.id === id);
}
