import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BadgeCheck, Building2, CalendarCheck2, MapPin, MessageCircle, ShieldCheck, Star, UsersRound } from "lucide-react";
import { FollowButton } from "@/components/follow-button";
import { PropertyCard } from "@/components/property-card";
import { getProfile, profiles, properties } from "@/lib/data";

export function generateStaticParams() { return profiles.map((profile) => ({ id: profile.id })); }
export default async function ProfilePage({ params }) {
  const { id } = await params; const profile = getProfile(id); if (!profile) notFound();
  const listings = properties.filter((property) => property.hostId === id);
  return <div className="profile-page"><section className="profile-cover"><Image src="/images/nestora/hero-abuja-residence.webp" alt="Contemporary Abuja home" fill priority sizes="100vw" /><span /></section><div className="shell profile-header"><div className="profile-avatar"><Image src={profile.avatar} alt={profile.name} fill sizes="150px" /></div><div className="profile-identity"><p className="verified-line verified-line--light"><BadgeCheck size={17} /> Identity and professional details verified</p><h1>{profile.name}</h1><strong>{profile.role} · {profile.company}</strong><p><MapPin size={15} />{profile.location}</p></div><div className="profile-actions"><FollowButton id={profile.id} /><Link href={`/messages?to=${profile.id}`} className="button button--ink"><MessageCircle size={17} />Message</Link></div></div><div className="shell profile-layout"><main><nav className="profile-tabs"><a href="#about" className="active">About</a><a href="#listings">Listings</a><a href="#reviews">Reviews</a><a href="#posts">Posts</a></nav><section id="about" className="profile-about"><h2>About {profile.name.split(" ")[0]}</h2><p>{profile.bio}</p><div className="profile-credentials"><span><ShieldCheck size={20} /><b>Identity checked</b><small>Government-issued identification reviewed</small></span><span><Building2 size={20} /><b>Business checked</b><small>Professional details and contact verified</small></span><span><CalendarCheck2 size={20} /><b>Active since 2020</b><small>Consistent activity and response history</small></span></div></section><section id="listings" className="profile-listings"><div className="section-heading"><div><p className="eyebrow">Current portfolio</p><h2>{listings.length} places represented</h2></div></div><div className="property-grid property-grid--profile">{listings.map((property) => <PropertyCard key={property.id} property={property} />)}</div></section><section id="reviews" className="profile-reviews"><h2>What clients say</h2><article><Star size={18} fill="currentColor" /><p>“Amina never rushed the process. Her viewing notes were accurate, her cost summary was complete, and every follow-up arrived when promised.”</p><strong>Chidi N. · Rental client</strong></article></section></main><aside className="profile-aside"><div><span><strong>{profile.followers.toLocaleString()}</strong>Followers</span><span><strong>{profile.listings}</strong>Listings</span><span><strong>4.96</strong>Rating</span></div><p><UsersRound size={17} />{profile.response}</p><Link href={`/messages?to=${profile.id}`} className="button button--coral">Start a conversation</Link><small>Keep messages and payments on Nestora for a safer, documented experience.</small></aside></div></div>;
}
